#!/bin/bash

### BEGIN INIT INFO
# Provides: Micro Nabto tunnel
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: the nabto tunnel server peer
# Description: the nabto tunnel server peer
### END INIT INFO

PIDFILE=/var/run/unabto_tunnel_testing.pid
EXEC=/usr/bin/unabto_tunnel_testing

source /etc/unabto_tunnel_testing.conf

if [[ $DEFAULT_HOST ]]; then
    DEFAULT_HOST_ARG="-H $DEFAULT_HOST"
fi

if [[ $DEFAULT_PORT ]]; then
    DEFAULT_PORT_ARG="-P $DEFAULT_PORT"
fi

function start {
    start-stop-daemon -b -c $USER -m -p $PIDFILE --exec $EXEC --start -- -p 0 -s -d $SERVERNAME $DEFAULT_HOST_ARG $DEFAULT_PORT_ARG
}

function stop {
    start-stop-daemon --exec $EXEC --stop --user $USER
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop || true
        ;;
    restart)
        stop
	sleep 1
        start
        ;;
    *)
        echo "usage: $0 (start|stop|restart)"
        exit 1
        ;;
esac
