#ifndef UNABTO_CONFIG_H
#define UNABTO_CONFIG_H

#define NABTO_ENABLE_TEST_CODE 1

#define NABTO_SET_TIME_FROM_ALIVE 0
#define NABTO_ENABLE_STREAM 0

#define NABTO_ENABLE_CLIENT_ID 1

#define NABTO_APPLICATION_EVENT_MODEL_ASYNC 1

#define NABTO_LOG_ALL 0

#define NABTO_ENABLE_EVENTCHANNEL 1

#endif
