name: C/C++ CI

on:
  push:
  release:
    types: [ published ]

jobs:
  build-and-test:
    name: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    steps:
    - uses: actions/checkout@v6

    - name: configure cmake
      run: mkdir build-dir && cd build-dir && cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts ..

    - name: build
      run: cmake --build build-dir --parallel

    - name: install
      run: cmake --build build-dir --target install

    - if: matrix.os == 'windows-2025'
      name: Test run
      run: |
        netsh advfirewall firewall add rule name="unabto_unittest" dir=in action=allow program="${{ github.workspace }}\artifacts\bin\unabto_unittest.exe" enable=yes
        ${{ github.workspace }}/artifacts/bin/unabto_unittest
    - if: matrix.os != 'windows-2025'
      name: Test run
      run: ${{ github.workspace }}/artifacts/bin/unabto_unittest

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v7
      with:
        name: artifacts_${{matrix.os}}
        path: ${{ github.workspace }}/artifacts
        if-no-files-found: warn

  release-assets:
    name: Release Assets
    needs: build-and-test
    runs-on: ubuntu-24.04
    permissions:
      # allow assets to be uploaded to a release
      contents: write
    strategy:
      matrix:
        binary: [unabto_tunnel]
    if: github.event_name == 'release' && success()
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifacts_ubuntu-24.04
          path: linux
      - uses: actions/download-artifact@v8
        with:
          name: artifacts_windows-2025
          path: windows
      - uses: actions/download-artifact@v8
        with:
          name: artifacts_macos-15
          path: macos
      - name: List assets
        run: ls -R
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux/bin/${{ matrix.binary }}
            windows/bin/${{ matrix.binary }}.exe
            macos/bin/${{ matrix.binary }}
